"""Drop location field on clinics table

Revision ID: 4b5323a13502
Revises: 60a0cfee744e
Create Date: 2025-04-15 12:35:26.928252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b5323a13502'
down_revision: Union[str, None] = '60a0cfee744e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinics', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinics', sa.Column('location', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###
