"""Add example clinics

Revision ID: 51cf1afa754f
Revises: 4b5323a13502
Create Date: 2025-04-15 12:49:39.199072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from datetime import datetime
from sqlalchemy import orm
from manage.models import Clinic, ClinicStatus, ClinicType, RiskType

# revision identifiers, used by Alembic.
revision: str = '51cf1afa754f'
down_revision: Union[str, None] = '4b5323a13502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Get the SQLAlchemy session
    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)
    # Create test clinics using the Clinic model
    test_clinics = [
        Clinic(
            setting="West Sussex BSS",
            starts_at=datetime(2025, 4, 16, 9, 0),
            ends_at=datetime(2025, 4, 16, 17, 0),
            status=ClinicStatus.SCHEDULED,
            type=ClinicType.SCREENING,
            risk_type=RiskType.MIXED_RISK
        ),
        Clinic(
            setting="Mobile Unit JA1 CP7 at Tesco Extra Banbury",
            starts_at=datetime(2025, 4, 17, 9, 0),
            ends_at=datetime(2025, 4, 17, 17, 0),
            status=ClinicStatus.IN_PROGRESS,
            type=ClinicType.ASSESSMENT,
            risk_type=RiskType.ROUTINE_RISK
        )
    ]
       
    # Add all clinics to the session
    session.add_all(test_clinics)
    session.commit()  
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Delete test clinics
    op.execute("""
        DELETE FROM clinics 
        WHERE setting IN ('West Sussex BSS', 'Mobile Unit JA1 CP7 at Tesco Extra Banbury')
    """)
    # ### end Alembic commands ###
